version: "3.9"

services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "883:883"
    volumes:
      - ./downloads:/usr/src/app/downloads
    environment:
      DATABASE_URL: postgres://postgres:supersecret@db:5432/app_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: Minecraft-Server-Website-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d  # <-- Mount init scripts here
    ports:
      - "5432:5432"

volumes:
  db_data: