- name: Build Docker image
  run: |
    docker build -t Minecraft-Server-Website:latest .

- name: Push Docker image
  run: |
    docker tag Minecraft-Server-Website:latest ${{ secrets.DOCKER_USERNAME }}/Minecraft-Server-Website:latest
    docker push ${{ secrets.DOCKER_USERNAME }}/Minecraft-Server-Website:latest

- name: Deploy via SSH
  if: ${{ secrets.DEPLOY_SERVER_IP != '' }}
  uses: appleboy/ssh-action@v0.1.7
  with:
    host: ${{ secrets.DEPLOY_SERVER_IP }}
    username: ${{ secrets.DEPLOY_SERVER_USER }}
    key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
    script: |
      cd ~/Minecraft-Server-Website   # match your repo name
      git pull origin main
      chmod +x start.sh
      ./start.sh